{"name": "Тест отображения заказа пользователя в ленте заказов и в истории заказов", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:509:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "self = <test_order_feed.TestsOrderFeed object at 0x000002AA9FE755B0>, driver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"03674698-fd02-41ba-9598-052cfa29df51\")>\nuser = {'email': 'eoyiubuhiu@yandex.ru', 'json': {'accessToken': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZGI...True, 'user': {'email': 'eoyiubuhiu@yandex.ru', 'name': 'eoyiubuhiu'}}, 'name': 'eoyiubuhiu', 'password': 'njtqosuznd'}\n\n    @allure.title('Тест отображения заказа пользователя в ленте заказов и в истории заказов')\n    def test_displaying_user_order_in_order_feed(self, driver, user):\n        order_feed_page = OrderFeedPage(driver)\n        order_feed_page.transition_site(Url.LOGIN)\n        order_feed_page.login_to_account(user[\"email\"], user[\"password\"])\n        order_feed_page.transferring_ingredient_constructor()\n        order_feed_page.click_button_place_an_order()\n        num_order = order_feed_page.get_num_order()\n        order_feed_page.click_button_close_pop_up_window()\n        order_feed_page.transition_to_order_feed()\n>       assert order_feed_page.searching_item_by_order_number(num_order)\n\ntests\\test_order_feed.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\order_feed_page.py:40: in searching_item_by_order_number\n    return self.find_element_located(str_num_order)\npages\\base_page.py:21: in find_element_located\n    return WebDriverWait(self.driver, time).until(ec.element_to_be_clickable(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"03674698-fd02-41ba-9598-052cfa29df51\")>, method = <function element_to_be_clickable.<locals>._predicate at 0x000002AA9FF30C20>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:509:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n.venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException"}, "steps": [{"name": "Вход в аккаунт", "status": "passed", "parameters": [{"name": "email", "value": "'eoyiubuhiu@yandex.ru'"}, {"name": "password", "value": "'njtqosuznd'"}], "start": 1708861888290, "stop": 1708861888703}, {"name": "Перенос ингредиента в конструктор", "status": "passed", "start": 1708861888704, "stop": 1708861889782}, {"name": "Клик по кнопке оформить заказ", "status": "passed", "start": 1708861889782, "stop": 1708861890013}, {"name": "Получить номер заказа", "status": "passed", "start": 1708861890014, "stop": 1708861895039}, {"name": "Клик по кнопке закрытия всплывающего окна", "status": "passed", "start": 1708861895039, "stop": 1708861895280}, {"name": "Переход к ленте заказов", "status": "passed", "start": 1708861895280, "stop": 1708861895515}, {"name": "Поиск элемента по номеру заказа", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:509:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\selez\\PycharmProjects\\Diplom\\Diplom_3\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\selez\\PycharmProjects\\Diplom\\Diplom_3\\pages\\order_feed_page.py\", line 40, in searching_item_by_order_number\n    return self.find_element_located(str_num_order)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\selez\\PycharmProjects\\Diplom\\Diplom_3\\pages\\base_page.py\", line 21, in find_element_located\n    return WebDriverWait(self.driver, time).until(ec.element_to_be_clickable(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\selez\\PycharmProjects\\Diplom\\Diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "parameters": [{"name": "num_order", "value": "'9999'"}], "start": 1708861895515, "stop": 1708861927053}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1708861886451, "stop": 1708861927057, "uuid": "24c0cffa-23a1-4f4e-a2c6-cd75ec2f3ade", "historyId": "951646ca11e4db52996313e5909da852", "testCaseId": "c2fbd0078113a2c069facdf9aba1ff25", "fullName": "tests.test_order_feed.TestsOrderFeed#test_displaying_user_order_in_order_feed", "labels": [{"name": "story", "value": "Тесты ленты заказов"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_feed"}, {"name": "subSuite", "value": "TestsOrderFeed"}, {"name": "host", "value": "Asus"}, {"name": "thread", "value": "6388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_feed"}]}